[dispatcher]
id = "disp_cs1-ff00_0_110-1"
local_udp_forwarding = true

[metrics]

[features]

[api]

[dispatcher.service_addresses]
"1-ff00:0:110,CS" = "172.20.0.20:30252"
"1-ff00:0:110,DS" = "172.20.0.20:30252"

[log.console]
level = "debug"
