[dispatcher]
id = "disp_cs1-ff00_0_112-1"
local_udp_forwarding = true

[metrics]

[features]

[api]

[dispatcher.service_addresses]
"1-ff00:0:112,CS" = "[fd00:f00d:cafe::7f00:13]:30252"
"1-ff00:0:112,DS" = "[fd00:f00d:cafe::7f00:13]:30252"

[log.console]
level = "debug"
