[general]
id = "sd1-ff00_0_112"
config_dir = "/etc/scion"

[trust_db]
connection = "/share/cache/sd1-ff00_0_112.trust.db"

[path_db]
connection = "/share/cache/sd1-ff00_0_112.path.db"

[sd]
address = "[fd00:f00d:cafe::7f00:14]:30255"

[tracing]
enabled = true
debug = true
agent = "172.17.0.1:6831"

[metrics]
prometheus = "[fd00:f00d:cafe::7f00:14]:30455"

[features]

[api]
addr = "[fd00:f00d:cafe::7f00:14]:30955"

[log.console]
level = "debug"
