[general]
id = "sd1-ff00_0_111"
config_dir = "/etc/scion"

[trust_db]
connection = "/share/cache/sd1-ff00_0_111.trust.db"

[path_db]
connection = "/share/cache/sd1-ff00_0_111.path.db"

[sd]
address = "192.168.123.3:30255"

[tracing]
enabled = true
debug = true
agent = "172.17.0.1:6831"

[metrics]
#prometheus = "172.20.0.28:30455"

[features]

[api]
addr = "192.168.123.3:30955"

[log.console]
level = "debug"
